// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWNDCkmy7-mnIT2KmSf68xzYJ5_bg3HxY',
    appId: '1:362233249667:web:2e0d61c4885face45200b6',
    messagingSenderId: '362233249667',
    projectId: 'loginsignup-3cca8',
    authDomain: 'loginsignup-3cca8.firebaseapp.com',
    storageBucket: 'loginsignup-3cca8.firebasestorage.app',
    measurementId: 'G-TWXT8Z2QE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB8vCSMUHq9sqpSC9LABAXK-BfXWVBXiQ',
    appId: '1:362233249667:android:6ad724994255e44c5200b6',
    messagingSenderId: '362233249667',
    projectId: 'loginsignup-3cca8',
    storageBucket: 'loginsignup-3cca8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfmrCSYgqX2DwqKO3vjPiikDA_j7PonrA',
    appId: '1:362233249667:ios:a2526c50d1bf27b05200b6',
    messagingSenderId: '362233249667',
    projectId: 'loginsignup-3cca8',
    storageBucket: 'loginsignup-3cca8.firebasestorage.app',
    iosBundleId: 'com.learning.learnapp.learnapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfmrCSYgqX2DwqKO3vjPiikDA_j7PonrA',
    appId: '1:362233249667:ios:a2526c50d1bf27b05200b6',
    messagingSenderId: '362233249667',
    projectId: 'loginsignup-3cca8',
    storageBucket: 'loginsignup-3cca8.firebasestorage.app',
    iosBundleId: 'com.learning.learnapp.learnapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWNDCkmy7-mnIT2KmSf68xzYJ5_bg3HxY',
    appId: '1:362233249667:web:13460ec6a70b21595200b6',
    messagingSenderId: '362233249667',
    projectId: 'loginsignup-3cca8',
    authDomain: 'loginsignup-3cca8.firebaseapp.com',
    storageBucket: 'loginsignup-3cca8.firebasestorage.app',
    measurementId: 'G-XDQJHSLDJW',
  );
}
